language:
  python
python:
- "3.6"
- "3.7"
- "3.8"
# install dependencies
install:
- pip install -r requirements.txt
- pip install codecov pdoc3 pytest pytest-cov
# run tests
script:
- pytest
- coverage run -m pytest
after_success:
  - codecov