language:
  python
python:
- "3.6"
- "3.7"
- "3.8"
# install dependencies
install:
- pip install -r src/requirements.txt
- pip install codecov
# run tests
script:
- pytest
- coverage run -m pytest
after_success:
  - codecov